### ISSUE TITLE
Cloudflare Pages

### ISSUE THREAD

**Issue by JeffHochberg** [captn3m0/hello-cloudflare#8]
Switch from GitHub Pages to Cloudflare Pages. Then you just configure Cloudflare Pages to connect to your GitHub Repositories.

Anytime you commit to your repositories that are connected to Cloudflare Pages, Pages will automatically kick off a build and your site will be updated within a couple of minutes or so.

**Comment by ignoramous** [comment]
The problem here is two fold:

1. GitHub pages is where existing websites are at.
2. [Defaults matter](https://blog.codinghorror.com/the-power-of-defaults/). And the default with Cloudflare is *Flexible SSL*, which is atrociously misleading in cases like these when a Cloudflare peer (like Airtel) mucks with Cloudflare's customer traffic (albeit under government guidance). [From this Cloudflare CTO's past interview on VPNs](https://news.ycombinator.com/item?id=19774347), it doesn't look like they care about it (government censorship) *enough*, though.

None of this is addressed with pages.dev. In fact, you'd want to not put more stuff on Cloudflare when GitHub Pages is plenty *fast* and vends free TLS/SSL certs.

**Comment by captn3m0** [comment]
Discussing Cloudflare Pages is out of scope of this letter. The ground reality is that enough projects and users are using Cloudflare against GitHub Pages  and we can't realistically get everyone off this combination (to any solution) to fix the problem for folks in India. 

Enabling Strict SSL is the fastest and easiest fix for now, which is why that's the current recommendation.

**Comment by captn3m0** [comment]
Added [a third fix](https://github.com/captn3m0/hello-cloudflare/blob/main/README.md#help-my-website-is-blocked) on switching to a different provider.

Thanks!
